"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['view.py']
DATA_FILES = ['gui']
OPTIONS = {
    'iconfile': 'gui/logo.icns',
    'packages': ['PyQt5'],
}

setup(
    app=APP,
    name='speedtester',
    version='1.0',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
